version: "3.11"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/your-db-name
    volumes:
      - ./backend:/usr/src/app

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    environment:
      - NODE_ENV=production
    volumes:
      - ./frontend:/usr/src/app

volumes:
  mongodata:
